/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SummarizeIndexRouteImport } from './routes/summarize/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAnalysisIdRouteImport } from './routes/dashboard/$analysisId'
import { Route as ApiRazorpayWebhookRouteImport } from './routes/api/razorpay/webhook'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SummarizeIndexRoute = SummarizeIndexRouteImport.update({
  id: '/summarize/',
  path: '/summarize/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAnalysisIdRoute = DashboardAnalysisIdRouteImport.update({
  id: '/dashboard/$analysisId',
  path: '/dashboard/$analysisId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRazorpayWebhookRoute = ApiRazorpayWebhookRouteImport.update({
  id: '/api/razorpay/webhook',
  path: '/api/razorpay/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/$analysisId': typeof DashboardAnalysisIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/summarize/': typeof SummarizeIndexRoute
  '/api/razorpay/webhook': typeof ApiRazorpayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/$analysisId': typeof DashboardAnalysisIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/summarize': typeof SummarizeIndexRoute
  '/api/razorpay/webhook': typeof ApiRazorpayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/$analysisId': typeof DashboardAnalysisIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/summarize/': typeof SummarizeIndexRoute
  '/api/razorpay/webhook': typeof ApiRazorpayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/pricing'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/$analysisId'
    | '/dashboard/'
    | '/summarize/'
    | '/api/razorpay/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/pricing'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/$analysisId'
    | '/dashboard'
    | '/summarize'
    | '/api/razorpay/webhook'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/pricing'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/$analysisId'
    | '/dashboard/'
    | '/summarize/'
    | '/api/razorpay/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  PricingRoute: typeof PricingRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  DashboardAnalysisIdRoute: typeof DashboardAnalysisIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  SummarizeIndexRoute: typeof SummarizeIndexRoute
  ApiRazorpayWebhookRoute: typeof ApiRazorpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summarize/': {
      id: '/summarize/'
      path: '/summarize'
      fullPath: '/summarize/'
      preLoaderRoute: typeof SummarizeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$analysisId': {
      id: '/dashboard/$analysisId'
      path: '/dashboard/$analysisId'
      fullPath: '/dashboard/$analysisId'
      preLoaderRoute: typeof DashboardAnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay/webhook': {
      id: '/api/razorpay/webhook'
      path: '/api/razorpay/webhook'
      fullPath: '/api/razorpay/webhook'
      preLoaderRoute: typeof ApiRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  PricingRoute: PricingRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  DashboardAnalysisIdRoute: DashboardAnalysisIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  SummarizeIndexRoute: SummarizeIndexRoute,
  ApiRazorpayWebhookRoute: ApiRazorpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
